apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
buildMetadata:
  - managedByLabel
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: kobold
  - pairs:
      app.kubernetes.io/version: latest
resources:
  - ./rbac.yaml
  - ./service.yaml
  - ./deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: kobold-config
    files:
      - ./etc/config.yaml
secretGenerator:
  - name: kobold-env
    envs:
      - ./etc/.env
