apiVersion: v1
kind: ServiceAccount
metadata:
  name: kobold
automountServiceAccountToken: true
imagePullSecrets: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: k8schain
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kobold-k8schain
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kobold
    namespace: default
roleRef:
  kind: Role
  name: k8schain
  apiGroup: rbac.authorization.k8s.io
