defaultBaseImage: gcr.io/distroless/static:nonroot
builds:
  - id: server
    main: ./cmd/server/
    env: [CGO_ENABLED=1]
    flags: [-tags, gitgo]
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.version={{.Env.VERSION}}
#
#
# To build with gitexec use the below:
#
# defaultBaseImage: index.docker.io/alpine/git:v2.36.3
# builds:
#   - id: server
#     main: ./cmd/server/
#     env: [CGO_ENABLED=0]
#     flags: [-tags, gitexec]
#     ldflags:
#       - -s -w
#       - -extldflags "-static"
#       - -X main.version={{.Env.VERSION}}
