apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kobold
spec:
  rules:
    - http:
        paths:
          - pathType: Exact
            path: /dockerhub/9a06938d-4022-46d3-8528-82cb95ee1ad5
            backend:
              service:
                name: kobold
                port:
                  name: http
