apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - managedByLabel
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: example
resources:
  - ../dist/
  - ./ingress.yaml
configMapGenerator:
  - name: kobold-config
    behavior: replace
    files:
      - ./etc/config.yaml
secretGenerator:
  - name: kobold-env
    behavior: replace
    envs:
      - ./etc/.env
