apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - managedByLabel
resources:
  - ../base/
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: kobold-config
    behavior: replace
    files:
      - ./etc/config.yaml
secretGenerator:
  - name: kobold-env
    behavior: replace
    envs:
      - ./etc/.env
  - name: dockerhub
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=etc/dockerconfig.json
patches:
  - target:
      kind: Deployment
      name: kobold
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -v=7
  - target:
      kind: ServiceAccount
      name: kobold
    patch: |
      - op: add
        path: /imagePullSecrets/-
        value:
          name: dockerhub
images:
  - name: index.docker.io/bluebrown/kobold
    newTag: dev
