name: pages

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set git config
        run: |
          git config --global user.email "noreply@bluebrown.github.io"
          git config --global user.name "GitHub Actions"

      - name: Build and publish the docs to github pages
        run: make github-pages
